name: trip_brain_app
description: A trip suggestion app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Layers
  trip_brain_domain:
    path: ./packages/trip_brain_domain
  trip_brain_ui:
    path: ./packages/trip_brain_ui
  trip_brain_data:
    path: ./packages/trip_brain_data

  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  provider: ^6.0.5
  google_fonts: ^4.0.4
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  store_redirect: ^2.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cert.pem
