name: trip_brain_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.2

dependencies:
  trip_brain_domain:
    path: ../trip_brain_domain/
  http: ^0.13.6
  protobuf: ^2.1.0
  grpc: ^3.1.0
  collection: ^1.17.1
  google_sign_in: ^6.1.3
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
